max_num_atoms=200
generations=100
population_size=50
lc=3.924
cross_over_rate=0.6
elite_fraction=0.1
initial_crowding_distance=0.1
niche_radius=0.1
alpha=1
initial_mutation_rate=1
mutation_rate_decay=0.993
fitness_func="L1"
reduction="sum"
[descriptors]
CN1=8.1
CN2=3.7
CN3=8
CN4=4.5
#flattening_pca":1
# "diameter_2radius":15.08
# "surface ratio":1
#"atom_number":85
#"Departure from sphere(moment)":0.0001
