sample_name="S1"
max_num_atoms=200
generations=150
population_size=300
lc=3.924
cross_over_rate=0.6
elite_fraction=0.01
fitness_weight=[1.0,1.0]
initial_crowding_distance=0.1
niche_radius=0.1
alpha=1
initial_mutation_rate=1
mutation_rate_decay=0.999
fitness_func="RAE" #RAE, L1,L2
reduction="max"   #mean max sum
plot_descriptors=["CN1","CN2","CN3","CN4","GCN1","oblateness_moment","atom_number","diameter_2radius","SVR_CN","surface_CN","surface_GCN"]
[descriptors]
atom_number=109
SVR_CN=0.77
#S3
#"diameter_2radius"=18.255
#"SVR_CN"=0.671

[save_config]
percentage=1



[plot_radar_conf]
save=true
descriptors=["CN1","GCN1","diameter_2radius","SVR_CN","oblateness_moment","atom_number"]
multiplier=[0.1,0.1,0.05,1.0,1.0,0.005]
#S1
#"diameter_2radius"=10.60
#"surface ratio"=0.8471
#S2
#"diameter_2radius"=13.68
#"surface ratio"=0.6491
#S4
#"diameter_2radius"=13.72
#"surface ratio"=0.6605
#A1
#"diameter_2radius"=9.42
#"surface ratio"=0.9177
#A2
#"diameter_2radius"=12.42
#"surface ratio"=0.9238
#CN1=8.1 #s2
#CN2=3.7
#CN3=8
#CN4=4.5
#diameter_2radius=12.08
#surface_ratio=0.7632
#flattening_pca":1
# "diameter_2radius":15.08
# "surface ratio":1
#"atom_number":85
#"Departure from sphere(moment)":0.0001
